-- Enable the pgvector extension
CREATE EXTENSION IF NOT EXISTS vector;

-- Table to store retrieved papers
CREATE TABLE IF NOT EXISTS papers (
    id TEXT PRIMARY KEY,
    title TEXT NOT NULL,
    abstract_text TEXT NOT NULL,
    content TEXT,
    
    -- Hybrid Search Columns
    -- 1. Keyword Search (BM25 via tsvector)
    search_vector tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english', coalesce(title, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(abstract_text, '')), 'B')
    ) STORED,
    
    -- 2. Semantic Search (pgvector)
    -- Assuming 1536 dimensions for OpenAI's text-embedding-3-small
    embedding vector(1536),
    
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Index for keyword search
CREATE INDEX IF NOT EXISTS papers_search_idx ON papers USING GIN (search_vector);

-- Index for vector search (HNSW is faster than IVFFlat for pgvector)
CREATE INDEX IF NOT EXISTS papers_embedding_idx ON papers USING hnsw (embedding vector_cosine_ops);

-- Table to store the structured summaries generated by the cheap LLM
CREATE TABLE IF NOT EXISTS paper_summaries (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    paper_id TEXT REFERENCES papers(id) ON DELETE CASCADE,
    method TEXT NOT NULL,
    core_idea TEXT NOT NULL,
    strengths JSONB NOT NULL DEFAULT '[]',
    weaknesses JSONB NOT NULL DEFAULT '[]',
    use_cases JSONB NOT NULL DEFAULT '[]',
    data_requirements TEXT,
    compute_cost TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Table to store experiment results
CREATE TABLE IF NOT EXISTS experiments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    method TEXT NOT NULL,
    parameters JSONB NOT NULL DEFAULT '{}',
    score DOUBLE PRECISION NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
